/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticleList: typeof import('./src/components/ArticleList.vue')['default']
    ImportDialog: typeof import('./src/components/ImportDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Toolbar: typeof import('./src/components/Toolbar.vue')['default']
    UApp: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_88909c41758f9c895f8291105eff5b5e/node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_88909c41758f9c895f8291105eff5b5e/node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_88909c41758f9c895f8291105eff5b5e/node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCheckbox: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_88909c41758f9c895f8291105eff5b5e/node_modules/@nuxt/ui/dist/runtime/components/Checkbox.vue')['default']
    UContextMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_88909c41758f9c895f8291105eff5b5e/node_modules/@nuxt/ui/dist/runtime/components/ContextMenu.vue')['default']
    UIcon: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_88909c41758f9c895f8291105eff5b5e/node_modules/@nuxt/ui/dist/runtime/vue/components/Icon.vue')['default']
    UInput: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_88909c41758f9c895f8291105eff5b5e/node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UModal: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_88909c41758f9c895f8291105eff5b5e/node_modules/@nuxt/ui/dist/runtime/components/Modal.vue')['default']
    USelect: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_88909c41758f9c895f8291105eff5b5e/node_modules/@nuxt/ui/dist/runtime/components/Select.vue')['default']
    USelectMenu: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_88909c41758f9c895f8291105eff5b5e/node_modules/@nuxt/ui/dist/runtime/components/SelectMenu.vue')['default']
    USlideover: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_88909c41758f9c895f8291105eff5b5e/node_modules/@nuxt/ui/dist/runtime/components/Slideover.vue')['default']
    UTooltip: typeof import('./node_modules/.pnpm/@nuxt+ui@4.9.0_88909c41758f9c895f8291105eff5b5e/node_modules/@nuxt/ui/dist/runtime/components/Tooltip.vue')['default']
  }
}
